// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewPost struct {
	ID      string `json:"id"`
	Title   string `json:"title"`
	Message string `json:"message"`
}

type Post struct {
	ID      string `json:"id"`
	Title   string `json:"title"`
	Message string `json:"message"`
}
